### ISSUE TITLE
Investigate NuclearCraft compatibility and settings

### ISSUE THREAD

**Issue by mskurnik** [MJCSStudios/1AQCraft#4]

**Comment by eighteenAM** [comment]
Balance seems good.

Things to consider:
- Hardcore containers?
  - A configurable amount of radiation can escape containers due to the items (or fluid) inside them.
  - When enabled, shielding can be added to tile entities (containers).
- Alternate scrubber mechanics?
  - Default is for scrubbers to remove ~12.5% of radiation in a chunk, if given 4 blocks air space in all directions (occlusion reduces effectiveness)
  -Alternate has the first scrubber remove 20% but adding more diminishes returns.
- Adding radiation to items?
  - Bananas
  - Uranium & Thorium tools

**Comment by eighteenAM** [comment]
Final pre-group-test NuclearCraft config pushed to repo.
